name: Process Repository-based Themes

on:
  # Run when catalog.json is modified
  push:
    branches: [main]
    paths:
      - 'Catalog/catalog.json'
  # Run manually
  workflow_dispatch:
  # Run on a schedule (weekly)
  schedule:
    - cron: '0 0 * * 0'  # Every Sunday at midnight

jobs:
  process-repos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Process Repository-based Themes
        run: python .github/scripts/process_repos.py

      - name: Commit Changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add Catalog/Themes/previews/ Catalog/Themes/manifests/ 
          git add Catalog/Components/*/previews/ Catalog/Components/*/manifests/
          git add Uploads/Themes/ Uploads/Components/
          git commit -m "Process repository-based themes" || echo "No changes to commit"
          git push
