name: Process Theme Submissions

on:
  push:
    branches: [main]
    paths:
      - 'Upload/push.json'
      - 'Upload/*.zip'
  workflow_dispatch:

jobs:
  process-submissions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Process Push File
        run: python .github/scripts/process_push.py

      - name: Commit Changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add -u Upload/
          git add Packages/ Catalog/ Upload/push.json
          git commit -m "Process theme submissions from push.json" || echo "No changes to commit"
          git push

      - name: Trigger Gallery Update
        if: success()
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: update-gallery