name: Update Theme Gallery

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Update Catalog"]
    types:
      - completed

jobs:
  update-gallery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Generate gallery
        run: |
          python .github/scripts/generate_gallery.py
          
      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add README.md .github/index
          git commit -m "Update theme gallery" || echo "No changes to commit"
          git push
